sudo: required

language: generic

services:
   - docker
before_install:
   - docker build -t dev-test -f ./frontend/dockerfile.dev ./frontend/ 
script:
   - docker run -e CI=true dev-test npm run test
